Serviço para salvar notificação
L-W-payments/asaas-payment pull request #106
Opened 2024-05-28 18:58 UTC by Wollace-Buarque

Nesse PR é adicionado um serviço de salvar notificação no banco de dados que será utilizado no futuro.

Tarefa: [Notificações - Criar service de salvar notificação](https://github.com/L-W-payments/asaas-payment/issues/94)

2024-05-28 19:45 UTC, luizfiliperm commented on grails-app/services/com/miniasaaslw/service/notification/NotificationService.groovy
> +    public void save(Customer customer, String title, String message, String url, NotificationPriority priority) {
Não seria melhor receber a notificação direto aqui?

2024-05-28 19:50 UTC, welingtonloh commented on src/main/groovy/com/miniasaaslw/entity/enums/NotificationPriority.groovy
> +    LOW,
Para já ir acostumando vcs ao coding style, sempre no topo da Enum entre o { e o primeiro item, deixem uma linha em branco

Isso vale para classes tbm

2024-05-28 19:50 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/notification/NotificationService.groovy
> +import grails.gorm.transactions.Transactional
Para ja ir se acostumando tbm

Uma linha em branco entre imports de pacotes diferentes

2024-05-28 19:50 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/notification/NotificationService.groovy
> +    public void save(Customer customer, String title, String message, String url, NotificationPriority priority) {
Vocês cogitaram usar adapter aqui ou um mapa para o método não ficar tão cheio de argumentos?

2024-05-28 19:50 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/notification/NotificationService.groovy
> +    private Notification buildNotificationProperties(Notification notification, Customer customer, String title,
Esse método é desnessário, façam o que precisam fazer no próprio save

2024-05-31 15:36 UTC, welingtonloh requested changes

2024-05-31 15:36 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/notification/NotificationService.groovy
> +    public void save(Customer customer, Map params) {
```suggestion
    public void save(Customer customer, Map notificationInfo) {
```

2024-05-31 15:36 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/notification/NotificationService.groovy
> +        notification.priority = NotificationPriority.valueOf(params.priority.toString().toUpperCase())
Vc nao ta enviando o item da Enum já?

Aqui ja deveria vir Enum, sem necessidade de converter

2024-05-31 19:14 UTC, luizfiliperm approved these changes

2024-06-01 01:41 UTC, welingtonloh approved these changes

2024-06-01 01:41 UTC, merged