Adicionando job para gerenciar a expiração cobrança
L-W-payments/asaas-payment pull request #113
Opened 2024-05-29 20:33 UTC by Wollace-Buarque

Nesse PR é adicionado o quartz para gerenciar o estado de uma cobrança.

### PR antecessor: [112](https://github.com/L-W-payments/asaas-payment/pull/112)

2024-05-29 20:38 UTC, luizfiliperm requested changes

2024-05-29 20:38 UTC, luizfiliperm commented on grails-app/jobs/com/miniasaaslw/jobs/PaymentExpirationJob.groovy
> +        cron name: "paymentExpirationJobTrigger", cronExpression: "0 0 0 ? * *" // Todos os dias a meia noite
Criar uma variável com essa cronExpression pra não ter que comentar o que faz

2024-05-31 15:38 UTC, welingtonloh requested changes

2024-05-31 15:38 UTC, welingtonloh commented on grails-app/jobs/com/miniasaaslw/jobs/PaymentExpirationJob.groovy
> +class PaymentExpirationJob {
Job deve iniciar sempre com verbo

2024-05-31 15:38 UTC, welingtonloh commented on grails-app/jobs/com/miniasaaslw/jobs/PaymentExpirationJob.groovy
> +        String everyDayAtMidnightExpression = "0 0 0 ? * *"
Não precisa dessa linha, passa a cron expression direto abaixo

2024-05-31 15:38 UTC, welingtonloh commented on grails-app/jobs/com/miniasaaslw/jobs/PaymentExpirationJob.groovy
> +        List<Payment> expiredPayments = PaymentRepository.query([
Mesmos comentarios que fiz por Slack

2024-05-31 20:05 UTC, luizfiliperm approved these changes

2024-06-01 01:41 UTC, welingtonloh commented on grails-app/jobs/com/miniasaaslw/jobs/ProcessOverduePaymentJob.groovy
> +        paymentService.processOverduePayment()
Coloquem um try catch aqui com log no catch

2024-06-01 01:41 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        if (payment.paymentStatus != PaymentStatus.PENDING) throw new RuntimeException(MessageUtils.getMessage("payment.errors.status.update.pending"))
!payment.paymentStatus.isPending()

2024-06-01 01:41 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +    public void updateToExpired(Long id) {
toOverdue

2024-06-01 01:41 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        payment.paymentStatus = PaymentStatus.EXPIRED
PaymentStatus.OVERDUE

2024-06-01 01:41 UTC, welingtonloh commented on src/main/groovy/com/miniasaaslw/repository/payment/PaymentRepository.groovy
> +                eq("paymentStatus", search.paymentStatus)
eq("paymentStatus", PaymentStatus.valueOf(search.paymentStatus))

da forma acima, caso passem um valor invalido, dá exception dai

2024-06-03 18:44 UTC, luizfiliperm requested changes

2024-06-03 18:44 UTC, luizfiliperm commented on grails-app/i18n/messages_pt_BR.properties
> +payment.errors.overdue=A data de vencimento já passou!
não usar "!"

2024-06-03 18:44 UTC, luizfiliperm commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
Não pode pagar uma cobrança vencida?

2024-06-04 15:44 UTC, TuiNascimento commented on src/main/groovy/com/miniasaaslw/repository/payment/PaymentRepository.groovy
> +            if (search.containsKey("paymentStatus")) {
se já estamos no contexto de payment, o nome do filtro precisa ser **payment**Status?

Acredito que apenas status já seria suficiente

2024-06-04 15:48 UTC, TuiNascimento commented on src/main/groovy/com/miniasaaslw/repository/payment/PaymentRepository.groovy
> +                        : PaymentStatus.valueOf(search.paymentStatus as String))
Para evitar esses ternários que geram complexidade na interpretação, pode adotar sempre o padrão 
`eq("campoEnum", Enum.valueOf(search.campoEnum.toString))`.

Apesar de fazer a conversão novamente caso já venha um Enum, é o padrão que usamos no Asaas

2024-06-04 15:49 UTC, TuiNascimento commented on src/main/groovy/com/miniasaaslw/repository/payment/PaymentRepository.groovy
> +            if (search.containsKey("paymentStatus")) {
agora que vi que o nome do campo no enum realmente é paymentStatus... ok. Segue assim mesmo

2024-06-04 15:51 UTC, TuiNascimento commented on grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy
> +        println("overduePendingPaymentsIdList: " + overduePendingPaymentsIdList)
remover logs de teste

2024-06-04 19:54 UTC, luizfiliperm approved these changes

2024-06-04 20:14 UTC, luizfiliperm approved these changes

2024-06-04 20:35 UTC, TuiNascimento commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +                    log.info("updatePendingPaymentStatus >> Erro ao atualizar status da cobrança de id: [${paymentId}] [Mensagem de erro]: ${exception.message}")
Se aconteceu um erro, log de erro e não info
```suggestion
                    log.error("PaymentService.updatePendingPaymentStatus >> Erro ao atualizar status da cobrança de id: [${paymentId}] [Mensagem de erro]: ${exception.message}")
```

2024-06-04 20:36 UTC, TuiNascimento commented on grails-app/jobs/com/miniasaaslw/jobs/ProcessOverduePaymentJob.groovy
> +        cron name: "expirePaymentJobTrigger", cronExpression: "0 0/10 0-13 ? * *"
Por padrão o nome do Trigger é sempre `nomeDoJobTrigger`

2024-06-04 20:36 UTC, TuiNascimento commented on grails-app/jobs/com/miniasaaslw/jobs/ProcessOverduePaymentJob.groovy
> +        cron name: "expirePaymentJobTrigger", cronExpression: "0 0/10 0-13 ? * *"
```suggestion
        cron name: "ProcessOverduePaymentJobTrigger", cronExpression: "0 0/10 0-13 ? * *"
```

2024-06-04 20:40 UTC, TuiNascimento commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        ]).list() as List<Long>
Esse job roda de 10 em 10 minutos, da 00:00 até 13:00. 

Porém aqui vemos que na primeira execução, ele já vai pegar todas as cobranças vencidas e fazer tudo de uma vez..

Questionamentos:
- Se o job faz tudo de uma vez, precisamos de uma trigger que executa várias vezes por dia?
- Será que é saudável uma única execução do job fazer o trabalho em TODAS as cobranças que vencem naquele dia? Lembrem que isso consome recursos (memória, cpu) e o Asaas tem milhões de cobranças vencendo todos os dias

2024-06-04 20:40 UTC, Wollace-Buarque commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +                    log.info("updatePendingPaymentStatus >> Erro ao atualizar status da cobrança de id: [${paymentId}] [Mensagem de erro]: ${exception.message}")
O wel me passou com o `info`, mas já foi resolvido

2024-06-04 20:42 UTC, Wollace-Buarque commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        ]).list() as List<Long>
Antes eu tinha feito para passar somente uma vez a meia noite, mas conversando com o Wel ficou resolvido de deixar entre 00:00 e 13h. 

Ele tinha pedido pra fazer algo que se repetisse porquê caso desse algum erro iria tentar novamente

2024-06-04 20:44 UTC, Wollace-Buarque commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        ]).list() as List<Long>
Sobre passar por todas de uma vez eu entendi o ponto, mas como seria outra forma de otimizar isso?

2024-06-04 20:54 UTC, TuiNascimento commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        ]).list() as List<Long>
Usa um limit X na query, assim cada execução só vai processar no máximo X itens, e as próximas vão fazer o restante

2024-06-04 20:56 UTC, TuiNascimento commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        ]).list() as List<Long>
https://gorm.grails.org/latest/hibernate/manual/index.html#_listing_instances

2024-06-04 20:57 UTC, TuiNascimento commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        ]).list() as List<Long>
vc pode usar .list(max: X) para fazer esse limite

2024-06-04 21:32 UTC, TuiNascimento approved these changes

2024-06-04 21:33 UTC, merged