Adicionando Repositório Base
L-W-payments/asaas-payment pull request #119
Opened 2024-05-31 20:17 UTC by luizfiliperm

### Impacto
Neste PR é adicionando o repositório base, para depois implementar nos repositories dos domains

### PR Predecessora

### Link da tarefa
https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=65222922

### Prints do desenvolvimento

2024-05-31 20:33 UTC, Wollace-Buarque requested changes

2024-05-31 20:33 UTC, Wollace-Buarque commented on src/main/groovy/com/miniasaaslw/repository/Repository.groovy
> +    public <T> T get(Class<T> responseType) {
Não tem porque adicionar um método que não é pra ser usado, pode remover

2024-05-31 20:33 UTC, Wollace-Buarque commented on src/main/groovy/com/miniasaaslw/repository/Repository.groovy
> +    public <T> PagedResultList<T> list(Class<T> responseType, Map params = [:]) {
Aqui também, remover o método que não deve ser utilizado

2024-05-31 20:33 UTC, Wollace-Buarque commented on src/main/groovy/com/miniasaaslw/repository/Repository.groovy
> +        String databaseColumnName = StringUtils.camelCaseToSnakeCase(fieldName)
De onde vem esse `StringUtils.camelCaseToSnakeCase`? Precisa criar ele

2024-06-01 01:37 UTC, welingtonloh approved these changes

2024-06-01 04:18 UTC, Wollace-Buarque approved these changes

2024-06-03 16:51 UTC, merged