Adicionando filtro para exibir pagadores deletados
L-W-payments/asaas-payment pull request #128
Opened 2024-06-03 22:32 UTC by luizfiliperm

### Impacto

Agora é possível visualizar pagadores que foram deletados, para futuramente ser possível restaurá-los

Foi adicionado um botão de "restaurar" que por enquanto ainda não é funcional, é só um indicativo de que aquele pagador em específico na listagem está deletado

### PR Predecessora
[81](https://github.com/L-W-payments/asaas-payment/pull/81)

### Link da tarefa

https://github.com/orgs/L-W-payments/projects/1?pane=issue&itemId=65886613

### Prints do desenvolvimento

Tela com o filtro:
![image](https://github.com/L-W-payments/asaas-payment/assets/79930607/19efc68c-c8f6-47a6-8582-fce9876fab62)

Quando é aplicado o filtro de exibir deletados:

![image](https://github.com/L-W-payments/asaas-payment/assets/79930607/b8a6714b-e89a-46f8-a6ef-2801ac56f68a)

2024-06-03 22:37 UTC, Wollace-Buarque approved these changes

2024-06-04 16:14 UTC, TuiNascimento commented on grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy
> +        if (params.name) search."name[like]" = params.name
Será que conseguimos incluir o `name` no filters também?
Acredito que facilitaria se todos os parâmetros viessem de um lugar só , em vez de parte do `filters` e outra parte dos `params`

2024-06-04 16:15 UTC, TuiNascimento commented on grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy
> +            if (filters.contains("includeDeleted")) search.includeDeleted = true
não tem a chance includeDeleted vir `false` ?

2024-06-04 16:57 UTC, luizfiliperm commented on grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy
> +            if (filters.contains("includeDeleted")) search.includeDeleted = true
Não, no filtro, quando vc seleciona "Exibir deletados" é mandado o value "includeDeleted", não é um map de"includeDeleted: true" por exemplo

2024-06-04 16:58 UTC, luizfiliperm commented on grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy
> +        if (params.name) search."name[like]" = params.name
o `filters` é uma lista
e não um map, por isso eles vêm separados

2024-06-04 20:19 UTC, Wollace-Buarque requested changes

2024-06-04 20:19 UTC, Wollace-Buarque commented on grails-app/assets/javascripts/PayerListController.js
> +    var filterReference = reference.querySelector(".js-payer-filter-input")
```suggestion
    var filterReference = reference.querySelector(".js-payer-filter-input");
```

2024-06-04 20:19 UTC, Wollace-Buarque commented on grails-app/assets/javascripts/PayerListController.js
> +            tableReference.params = filterData
```suggestion
            tableReference.params = filterData;
```

2024-06-04 20:25 UTC, Wollace-Buarque approved these changes

2024-06-04 22:10 UTC, TuiNascimento approved these changes

2024-06-04 22:10 UTC, merged