Adicionando filtro para exibir cobranças deletadas
L-W-payments/asaas-payment pull request #131
Opened 2024-06-03 22:57 UTC by luizfiliperm

### Impacto

Agora é possível visualizar cobranças que foram deletadas, para futuramente ser possível restaurá-las

Foi adicionado um botão de "restaurar" que por enquanto ainda não é funcional, é só um indicativo de que aquela cobrança em específico na listagem está deletada

### PR Predecessora

[90](https://github.com/L-W-payments/asaas-payment/pull/90)

### Link da tarefa

[124](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=65886600)

### Prints do desenvolvimento

Filtro desativado:
![image](https://github.com/L-W-payments/asaas-payment/assets/79930607/5e832b12-ef22-41d7-943e-ce5aee33417e)

Filtro ativado:
![image](https://github.com/L-W-payments/asaas-payment/assets/79930607/c2084cc9-6b9a-4509-a236-b8e3d826001e)

2024-06-03 23:00 UTC, Wollace-Buarque approved these changes

2024-06-04 16:16 UTC, TuiNascimento commented
Mesmos comments do https://github.com/L-W-payments/asaas-payment/pull/128

2024-06-04 20:24 UTC, Wollace-Buarque requested changes

2024-06-04 20:24 UTC, Wollace-Buarque commented on grails-app/assets/javascripts/PaymentListController.js
> +        bindFilterReference()
```suggestion
        bindFilterReference();
```

2024-06-04 20:26 UTC, Wollace-Buarque approved these changes

2024-06-04 22:12 UTC, TuiNascimento approved these changes

2024-06-04 22:12 UTC, merged