Implementando notificações
L-W-payments/asaas-payment pull request #139
Opened 2024-06-04 23:16 UTC by Wollace-Buarque

### Impacto

Neste PR o sistema de notificações foi integrado com ações de pagamento, sendo eles alteração do estado de pagamento, exclusão, criação e restauração de um pagamento.

Também foram corrigidos erros importantes que aconteceram após os merges na main.  

### PR Predecessora

### Link da tarefa

### Prints do desenvolvimento

![image](https://github.com/L-W-payments/asaas-payment/assets/29075798/0e0b7826-ea99-43fd-95ab-f3ee1122fc96)

2024-06-05 16:55 UTC, luizfiliperm requested changes

2024-06-05 16:55 UTC, luizfiliperm commented on grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy
> +            flash.messageInfo = [messages: runtimeException.getMessage(), messageType: "error"]
```suggestion
            flash.messageInfo = [messages: [runtimeException.getMessage()], messageType: "error"]
```
O template tá esperando um map nas messages, mesma abordagem pros outros

2024-06-05 16:57 UTC, TuiNascimento commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        ])
O ideal seria utilizarmos um Adapter em vez de Map

2024-06-05 21:03 UTC, luizfiliperm approved these changes

2024-06-05 21:03 UTC, luizfiliperm commented on src/main/groovy/com/miniasaaslw/adapters/notification/NotificationAdapter.groovy
> +    private static final DATE_FORMAT = new SimpleDateFormat("dd 'de' MMM 'de' yyyy")
Manda isso aqui pro DateUtils

2024-06-05 21:05 UTC, luizfiliperm requested changes

2024-06-05 21:05 UTC, luizfiliperm commented on src/main/groovy/com/miniasaaslw/adapters/notification/NotificationAdapter.groovy
> +    private static final DATE_FORMAT = new SimpleDateFormat("dd 'de' MMM 'de' yyyy")
Manda isso aqui pro DateUtils

2024-06-06 15:51 UTC, TuiNascimento commented
verificar conflitos

2024-06-06 17:08 UTC, luizfiliperm approved these changes

2024-06-06 19:43 UTC, luizfiliperm requested changes

2024-06-06 19:43 UTC, luizfiliperm commented on src/main/groovy/com/miniasaaslw/utils/DateUtils.groovy
> +    public static final DATE_PARSER_FORMAT = new SimpleDateFormat("dd 'de' MMM 'de' yyyy")
Cria um método que retorna a String da data formatada

2024-06-06 21:38 UTC, luizfiliperm approved these changes

2024-06-07 00:01 UTC, TuiNascimento approved these changes

2024-06-07 00:01 UTC, merged