Usando a taglib de formatação de datas nos gsps
L-W-payments/asaas-payment pull request #155
Opened 2024-06-05 21:38 UTC by luizfiliperm

### Impacto
Agora está sendo usado a taglib de formatação de datas nos gsps

### PR Predecessora

### Link da tarefa
[108](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=65037209)

### Prints do desenvolvimento

2024-06-05 22:22 UTC, Wollace-Buarque requested changes

2024-06-05 22:22 UTC, Wollace-Buarque commented on grails-app/views/payer/templates/_tableContent.gsp
> +            ${dateTimeTagLib.datetime(date: payer.dateCreated)}
Não seria `dateTime`? Seguindo o padrão de camel case. 

Isso serve pra os outros também

2024-06-05 22:47 UTC, Wollace-Buarque approved these changes

2024-06-06 15:56 UTC, TuiNascimento approved these changes

2024-06-06 15:56 UTC, merged