Adapter de Notificações de email
L-W-payments/asaas-payment pull request #172
Opened 2024-06-06 19:54 UTC by luizfiliperm

### Impacto
É adicionado o adapter de notificações de email, buildando a mensagem que chegará por email a partir do message properties

### PR Predecessora
[167](https://github.com/L-W-payments/asaas-payment/pull/167)

### Link da tarefa
[171](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=66451264)

### Prints do desenvolvimento

2024-06-06 20:09 UTC, Wollace-Buarque requested changes

2024-06-06 20:09 UTC, Wollace-Buarque commented on src/main/groovy/com/miniasaaslw/adapters/emailNotification/EmailNotificationAdapter.groovy
> +    Boolean isSent
```suggestion
    Boolean sent
```

2024-06-06 21:04 UTC, Wollace-Buarque approved these changes

2024-06-07 17:22 UTC, TuiNascimento commented on grails-app/i18n/messages_pt_BR.properties
> +emailNotification.customer.body.payment.created=Você criou uma cobrança para {0}. No valor de R$ {1}, com vencimento em {2}.
Faz sentido enviarmos uma notificação para o próprio usuário que acabou de realizar a ação de criar a cobrança?

2024-06-07 17:23 UTC, TuiNascimento commented on grails-app/i18n/messages_pt_BR.properties
> +emailNotification.customer.body.payment.created=Você criou uma cobrança para {0}. No valor de R$ {1}, com vencimento em {2}.
Avaliar a mesma coisa para todas as notificações

2024-06-07 17:26 UTC, TuiNascimento commented on src/main/groovy/com/miniasaaslw/adapters/emailnotification/EmailNotificationAdapter.groovy
> +    public EmailNotificationAdapter buildPayerEmailPaymentCreated(Payment payment) {
havíamos conversado sobre usar métodos estáticos, não?

Para o uso ficar `EmailNotificationAdapter.buildPayerEmailPaymentCreated(payment)` em vez de `new EmailNotificationAdapter().buildPayerEmailPaymentCreated(payment)`, ficando mais simples

2024-06-07 18:15 UTC, TuiNascimento approved these changes

2024-06-07 18:15 UTC, merged