Refatorando notificações da aplicação e layout principal
L-W-payments/asaas-payment pull request #222
Opened 2024-06-11 20:14 UTC by Wollace-Buarque

### Impacto

Com essa alteração foi as notificações do usuário não se expandir até o fim da tela como acontecia antigamente. Também foi adicionado links de redirecionamento da notificação.

### PR Predecessora

### Link da tarefa

[Tarefa 221](https://github.com/L-W-payments/asaas-payment/issues/221)

### Prints do desenvolvimento

Antes da alteração:
![image](https://github.com/L-W-payments/asaas-payment/assets/29075798/3b7e7211-8c4d-4bfe-ab80-5d3cb1b408c7)

Depois da alteração:
![image](https://github.com/L-W-payments/asaas-payment/assets/29075798/4440215d-10cc-4c73-b78a-7b92bc32be91)

2024-06-11 20:35 UTC, luizfiliperm requested changes

2024-06-11 20:35 UTC, luizfiliperm commented on grails-app/controllers/com/miniasaaslw/controller/notification/NotificationController.groovy
> +            List<Notification> notifications = notificationService.list(LoggedCustomer.CUSTOMER.id)
Já da pra alterar pra pegar o id do customer do usuário logado
```suggestion
            List<Notification> notifications = notificationService.list((getAuthenticatedUser() as User).customerId)
```

2024-06-11 22:45 UTC, luizfiliperm approved these changes

2024-06-12 00:01 UTC, Thuran approved these changes

2024-06-12 00:03 UTC, merged