Refactor dueDate validate
L-W-payments/asaas-payment pull request #255
Opened 2024-06-13 19:02 UTC by luizfiliperm

### Impacto
É corrigido o erro de validação da data de vencimento
- Não era possível criar uma cobrança que se vence no dia atual
- Acontecia porque a gente tava comparando com uma instância `new Date()`, que pega o dia atual, mas também a hora
- Então na hora de comparar utilizando o `before`, retornava false

### Solução
- Foi criado um método no DateUtils que retorna a data atual as 00:00

### PR Predecessora

### Link da tarefa
[254](https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=67363975)

### Prints do desenvolvimento

2024-06-13 19:59 UTC, Thuran commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        if (dueDate.before(DateUtils.today())) return false
`(new Date()).clearTime()` não deveria resolver?

2024-06-13 20:00 UTC, Thuran requested changes

2024-06-13 20:00 UTC, Thuran commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        if (dueDate.before(DateUtils.today())) return false
com essa lib `api "org.codehaus.groovy:groovy-dateutil:3.0.16"` passamos a ter alguns utils para o date

2024-06-13 20:04 UTC, luizfiliperm commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        if (dueDate.before(DateUtils.today())) return false
Adicionado 👍🏼

2024-06-13 20:29 UTC, Wollace-Buarque approved these changes

2024-06-14 11:06 UTC, Thuran approved these changes

2024-06-14 11:06 UTC, merged