Relacionamento entre Customer e Payer
L-W-payments/asaas-payment pull request #36
Opened 2024-05-21 19:27 UTC by luizfiliperm

Neste PR é adcionado o relacionamento entre os domains customer e payer.

Além de adcionar um select no front para selecionar qual customer está relacionado ao novo payer

![image](https://github.com/L-W-payments/asaas-payment/assets/79930607/016f4621-7ac8-4668-8596-c1a9074c5e8a)

2024-05-22 11:33 UTC, Yuri-Ferrari requested changes

2024-05-22 11:33 UTC, Yuri-Ferrari commented on grails-app/services/com/miniasaaslw/service/customer/CustomerService.groovy
> +    }
Como esse método não tem uma regra de negócio e é um código simples, ele não precisa existir, podem usar direto o `CustomerRepository.query([:]).list()` nos lugares onde esse método é chamado

2024-05-22 11:33 UTC, Yuri-Ferrari commented on grails-app/services/com/miniasaaslw/service/payer/PayerService.groovy
> +        Payer updatePayer = find(id)
A nomenclatura dessa variável pode gerar confusão, pois `updatePayer` leva a pensar que isso é uma ação e não um objeto, mudem pra `payerToBeUpdated` ou apenas `payer`

2024-05-22 11:33 UTC, Yuri-Ferrari commented on grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy
> +            Payer payer = payerService.save(new PayerAdapter(params), customerId)
O customerID faz parte da criação do Payer, ele precisa estar dentro do Adapter para criá-lo

2024-05-23 16:51 UTC, Yuri-Ferrari requested changes

2024-05-23 16:51 UTC, Yuri-Ferrari commented on grails-app/services/com/miniasaaslw/service/payer/PayerService.groovy
> +        Payer payer = buildPayerProperties(new Payer(), payerAdapter, customerService.find(payerAdapter.customerId))
Como é uma query simples, não precisa injetar a dependência aqui, pode chamar diretamente a query do Repository

2024-05-23 16:51 UTC, Yuri-Ferrari commented on grails-app/services/com/miniasaaslw/service/payer/PayerService.groovy
> +    def customerService;
Groovy não precisa de ;

2024-05-23 17:06 UTC, Yuri-Ferrari requested changes

2024-05-23 17:06 UTC, Yuri-Ferrari commented on grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy
> +    def customerService
Não é utilizado

2024-05-23 17:06 UTC, Yuri-Ferrari commented on grails-app/services/com/miniasaaslw/service/payer/PayerService.groovy
> +        Payer payer = buildPayerProperties(new Payer(), payerAdapter, CustomerRepository.query(id : payerAdapter.customerId).get())
Não está sendo validado se o cliente existe antes de salvar o Payer

2024-05-23 17:10 UTC, luizfiliperm commented on grails-app/services/com/miniasaaslw/service/payer/PayerService.groovy
> +        Payer payer = buildPayerProperties(new Payer(), payerAdapter, CustomerRepository.query(id : payerAdapter.customerId).get())
Não seria melhor então realmente chamar o find do customerService, que já faz essa validação?
pq aí seria código duplicado

2024-05-23 19:32 UTC, Yuri-Ferrari approved these changes
Conflitos no PR, precisa realizar um merge da `main` nessa branch

2024-05-23 19:32 UTC, Yuri-Ferrari commented on grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy
> +        Long customerId = params.long("customerId")
Não tem uso

2024-05-23 19:38 UTC, merged