Passando mensagens da aplicação para message.properties
L-W-payments/asaas-payment pull request #77
Opened 2024-05-24 20:12 UTC by Wollace-Buarque

Nesse PR todas as mensagens que estão nos controllers e services para o message.properties

2024-05-28 19:18 UTC, welingtonloh commented
@Wollace-Buarque consegue validar e resolver os conflitos?

@luizfiliperm depois dele resolver os conflitos consegue revisar e aprovar?
Acho que será uma boa termos esse combinado, eu reviso somente depois o outro da dupla revisar e aprovar
Após os dois approves, ai está liberado o merge

2024-05-28 19:20 UTC, luizfiliperm commented
> @Wollace-Buarque consegue validar e resolver os conflitos?
> 
> @luizfiliperm depois dele resolver os conflitos consegue revisar e aprovar? Acho que será uma boa termos esse combinado, eu reviso somente depois o outro da dupla revisar e aprovar Após os dois approves, ai está liberado o merge



> @Wollace-Buarque consegue validar e resolver os conflitos?
> 
> @luizfiliperm depois dele resolver os conflitos consegue revisar e aprovar? Acho que será uma boa termos esse combinado, eu reviso somente depois o outro da dupla revisar e aprovar Após os dois approves, ai está liberado o merge



> @Wollace-Buarque consegue validar e resolver os conflitos?
> 
> @luizfiliperm depois dele resolver os conflitos consegue revisar e aprovar? Acho que será uma boa termos esse combinado, eu reviso somente depois o outro da dupla revisar e aprovar Após os dois approves, ai está liberado o merge

Certo, já vou alterar a forma em que a main está protegida

2024-05-28 19:26 UTC, Wollace-Buarque commented
> @Wollace-Buarque consegue validar e resolver os conflitos?
> 
> @luizfiliperm depois dele resolver os conflitos consegue revisar e aprovar? Acho que será uma boa termos esse combinado, eu reviso somente depois o outro da dupla revisar e aprovar Após os dois approves, ai está liberado o merge

Conflitos resolvidos

2024-05-28 19:31 UTC, luizfiliperm requested changes

2024-05-28 19:31 UTC, luizfiliperm commented on src/main/groovy/com/miniasaaslw/utils/MessageUtils.groovy
> +
Espaço a mais

2024-05-28 19:56 UTC, luizfiliperm approved these changes

2024-05-28 21:26 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        if (!payment) throw new RuntimeException(MessageUtils.getMessage("general.errors.notFound", ["Pagamento"]))
Galera não me parece uma boa esse lance de passar Pagamento como argumento

Criem então um:
payment.notFound=Cobrança não encontrada

Sugiro que revisem todos os demais pontos tbm

Não tem problema no message.properties termos entradas parecidas

2024-05-28 21:26 UTC, welingtonloh commented on grails-app/i18n/messages_pt_BR.properties
>  paymentStatus.APPROVED.label=Aprovado
Como comentei na daily hoje, revisem isso num novo PR

o certo por enquanto seria termos os status:
Pendente e Recebido

Não faz muito sentido esse status aprovado

Me expliquem aqui o que é esse cancelado?

2024-05-28 21:26 UTC, welingtonloh commented on grails-app/i18n/messages_pt_BR.properties
> +general.errors.duplicated={0} já existe!
Não usem "!", na nossa codebase irão notar que nao usamos tbm
Pode passar uma interpretação errada para quem lê

2024-05-28 21:40 UTC, luizfiliperm commented on grails-app/i18n/messages_pt_BR.properties
>  paymentStatus.APPROVED.label=Aprovado
"Expirado" também seria um status, n?

E o certo para o enum de recebido, seria "Paid" ou "Received" msm?

2024-05-28 21:41 UTC, Wollace-Buarque commented on grails-app/i18n/messages_pt_BR.properties
>  paymentStatus.APPROVED.label=Aprovado
Este "cancelado" foi alterado em outro PR para "expirado"

2024-05-31 14:52 UTC, welingtonloh commented on grails-app/i18n/messages_pt_BR.properties
>  paymentStatus.APPROVED.label=Aprovado
PENDING, RECEIVED, OVERDUE

2024-05-31 14:57 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/customer/CustomerService.groovy
> +{0}
```suggestion
```

2024-05-31 14:59 UTC, welingtonloh approved these changes

2024-05-31 14:59 UTC, merged