Funcionalidade de pagamento
L-W-payments/asaas-payment pull request #79
Opened 2024-05-24 22:40 UTC by Wollace-Buarque

Nesse PR é adicionado o endpoint de pagar uma cobrança, ligando ele com o botão na tela de uma cobrança específica.

2024-05-28 19:36 UTC, luizfiliperm requested changes

2024-05-28 19:36 UTC, luizfiliperm commented on grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy
> +            redirect(uri: "/payment/show/${id}")
```groovy
redirect(action: 'show', params: [id: id])
```

2024-05-28 20:07 UTC, luizfiliperm approved these changes

2024-05-28 21:43 UTC, welingtonloh commented on grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy
> +            redirect(action: 'show', id: id)
Pode aplicar nesse padrão para todos?

esse uri é estranho

2024-05-28 21:43 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +    public void pay(Long paymentId) {
Aproveitem esse PR e ajustem o item da Enum PaymentStatus, de approved para received

Aproveitem e orientem esse metodo na service e na controller para isso tbm:
pay >> updateToReceived

Em relação ao parâmetro: (Long paymentId) {
Utilizem Long id, pois nessa service PaymentService, quando estivermos falando de id, pela logica será um ID de payment

2024-05-28 21:43 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        Payment payment = PaymentRepository.query([id: paymentId]).get()
Aqui passem o customer já, mesmo que não tenham o springSecurity ainda

Vcs só podem alterar cobranças que seja do customer corrente, podem por enquanto criar uma constante para esse customer e passar ele hard coded mesmo

2024-05-28 21:43 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        if (!payment) throw new RuntimeException("Pagamento não encontrado!")
```suggestion
        if (!payment) throw new RuntimeException("Cobrança não encontrada!")
```

2024-05-28 21:43 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        if (new Date().after(payment.dueDate)) throw new RuntimeException("A data de vencimento já passou!")
Criem um metodo privado chamado validateUpdateToReceived e deixam as validações organizada la dentro dele

Exemplo:
AccountManager validatedAccountManager = validateCreate(accountManagerAdapter)
if (validatedAccountManager.hasErrors()) throw new ValidationException("Dados inválidos para salvar gerente", validatedAccountManager.errors)

2024-05-28 22:51 UTC, Wollace-Buarque commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        Payment payment = PaymentRepository.query([id: paymentId]).get()
Sobre o customer, esse método é feito para pessoas que não estão logadas, o pagador não vai entrar no site, ele entra em um link de uma cobrança e efetua o pagamento

2024-05-31 14:51 UTC, welingtonloh commented on grails-app/i18n/messages_pt_BR.properties
> +paymentStatus.EXPIRED.label=Vencida
OVERDUE

2024-05-31 15:10 UTC, welingtonloh commented on grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy
> +    def pay() {
```suggestion
    def updateToReceived() {
```

2024-05-31 15:10 UTC, welingtonloh commented on grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy
> +        Long id = params.long("id")
Pq codigo fora do try?

2024-05-31 15:10 UTC, welingtonloh commented on grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy
> +            paymentService.updateToReceived(id)
@Wollace-Buarque ID ou publicId? esse método será usado por pagador? pagador só sabe o publicId, geralmente só acessa um link com publicId

2024-05-31 15:10 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        }
```suggestion
        if (validatedPayment.hasErrors()) throw new ValidationException("Erro ao validar parâmetros da cobrança", validatedPayment.errors)
```
Quando for uma linha apenas, e dentro do { } tem um return ou um throw, que interrompem o codigo, podem fazer dessa maneira para deixar o codigo mais sucinto e rapido de ler

2024-05-31 15:10 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        if (new Date().after(payment.dueDate)) {
Tem certeza? nós nunca vamos poder receber cobranças vencidas?

2024-05-31 15:10 UTC, welingtonloh commented on grails-app/views/payment/checkout.gsp
> +                            description="${payment.getDescription() ?: 'Seu fornecedor não informou descrição para este serviço/produto.'}">
```suggestion
                            description="${payment.description ?: 'Seu fornecedor não informou descrição para este serviço/produto.'}">
```
Isso vale para todos, nao precisa de get

2024-05-31 15:10 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        if (payment.paymentStatus == PaymentStatus.RECEIVED) {
payment.paymentStatus.isReceived()

Criem esse metodo na Enum

Ai nao precisam deixar o codigo verboso com == PaymentStatus.RECEIVED sempre

2024-05-31 15:11 UTC, welingtonloh commented
Resolver os conflitos tbm

2024-05-31 18:18 UTC, Wollace-Buarque commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        if (new Date().after(payment.dueDate)) {
Por enquanto a gente decidiu deixar bloqueado

2024-05-31 18:24 UTC, Wollace-Buarque commented on grails-app/controllers/com/miniasaaslw/controller/payment/PaymentController.groovy
> +            paymentService.updateToReceived(id)
Alterei a variável para publicId, mas o **params.long("id")** eu deixei do mesmo jeito porque ele pega dinamicamente o Id da página. Ficou assim:

`Long publicId = params.long("id")`

2024-05-31 18:50 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        if (new Date().after(payment.dueDate)) {
@Wollace-Buarque nao faz sentido esse requisito man

2024-05-31 20:38 UTC, Wollace-Buarque commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        if (new Date().after(payment.dueDate)) {
Removido no PR de Jobs

2024-06-01 01:34 UTC, welingtonloh commented on grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
> +        Payment payment = PaymentRepository.query([id: id]).get()
Nos PRs subsquentes aqui precisa ser publicId

2024-06-01 01:34 UTC, welingtonloh approved these changes

2024-06-01 01:34 UTC, merged