Alertas
L-W-payments/asaas-payment pull request #80
Opened 2024-05-24 22:43 UTC by luizfiliperm

Neste PR é adcionado os Alertas de erro para as páginas do formulário

Exemplo:
![image](https://github.com/L-W-payments/asaas-payment/assets/79930607/53c3e5a7-d98b-4da6-8369-7a959a44e39c)

2024-05-28 19:30 UTC, Wollace-Buarque approved these changes

2024-05-28 21:48 UTC, welingtonloh commented on grails-app/views/utils/_alerts.gsp
> +<g:if test="${alerts && alertType}">
São alertas ou são mensagens de erro, e podem ser tbm mensagens de sucesso?

Acho melhor rever todo o PR em relação a isso

2024-05-28 21:48 UTC, welingtonloh commented on grails-app/views/payment/index.gsp
> +    <alertTagLib:showAlerts alerts="${errors}" alertType="error"/>
Precisa repetir a mesma coisa?

Recebam um mapa de informações da mensagem a ser exibida

Por exemplo, o alertType pode ser uma dessas props

2024-05-28 21:53 UTC, luizfiliperm commented on grails-app/views/utils/_alerts.gsp
> +<g:if test="${alerts && alertType}">
Pode ser usado tanto pra mensagem de erro, ou sucesso
vou alterar a descrição do PR, realmente tá errado

2024-05-31 15:15 UTC, welingtonloh requested changes

2024-05-31 15:15 UTC, welingtonloh commented on grails-app/taglib/com/miniasaaslw/AlertTagLib.groovy
> +        def alertInfo = attrs.alertInfo
Map messageInfo = ...

2024-05-31 15:15 UTC, welingtonloh commented on grails-app/taglib/com/miniasaaslw/AlertTagLib.groovy
> +                model: [alertInfo: alertInfo]
model: messageInfo

Senão fica mapa dentro de mapa

2024-05-31 15:15 UTC, welingtonloh commented on grails-app/controllers/com/miniasaaslw/controller/customer/CustomerController.groovy
> +        if(alertInfo){
```suggestion
        if (alertInfo){
```

2024-05-31 15:15 UTC, welingtonloh commented on grails-app/controllers/com/miniasaaslw/controller/customer/CustomerController.groovy
> +        if(alertInfo){
Utiliza os termos:
messageInfo
messageType

desvincula da ideia de alerta

2024-06-03 17:40 UTC, Wollace-Buarque requested changes

2024-06-03 17:40 UTC, Wollace-Buarque commented on grails-app/controllers/com/miniasaaslw/controller/customer/CustomerController.groovy
> +            redirect(action: 'show', params: [id: customer.id])
Vamos tentar padronizar o uso de aspas duplas em services/controller, exceto em alguns lugares do gsp.
Também vamos parar de utilizar o `uri` do redirect.

Tenta fazer essas alterações nas outras partes do código desse arquivo

```suggestion
            redirect(action: "show", id: customer.id)
```

2024-06-03 17:40 UTC, Wollace-Buarque commented on grails-app/controllers/com/miniasaaslw/controller/customer/CustomerController.groovy
>              runtimeException.printStackTrace()
Não utilizar stack traces

2024-06-03 19:44 UTC, Wollace-Buarque approved these changes

2024-06-03 19:45 UTC, luizfiliperm commented on grails-app/controllers/com/miniasaaslw/controller/customer/CustomerController.groovy
> +            redirect(action: 'show', params: [id: customer.id])
Foi criada uma issue pra refatorar isso em todo o cód
https://github.com/orgs/L-W-payments/projects/1/views/1?pane=issue&itemId=65250116

2024-06-04 14:27 UTC, TuiNascimento commented on grails-app/taglib/com/miniasaaslw/MessagesTagLib.groovy
> +    }
Precisamos mesmo dessa tagLib? 
A princípio parece que ela não implementa nenhum comportamento, apenas repassa os parâmetros para o `render`.

Nesse caso, pq não usar direto 
`<g:render template="/utils/messages" model="${messageInfo}"/>`

lá no gsp?

2024-06-04 20:41 UTC, TuiNascimento approved these changes

2024-06-04 20:54 UTC, merged